### ISSUE TITLE
Mac OSX : "Could not open library 'libopenal.dylib': dlopen(libopenal.dylib, 5): image not found"

### ISSUE THREAD

**Issue by arnlen** [npomf/openal-ruby#2]
Mac OSX El Capitan version `10.11.5`

I've installed OpenAL-soft with brew, and I can see the `libopenal.dylib` file inside `/usr/local/opt/openal-soft/lib`.

How can I make it detectable by the gem?

---

For reference, here is the output of the `brew install` command:

```shell
$ brew install openal-soft
==> Downloading https://homebrew.bintray.com/bottles/openal-soft-1.17.2.el_capitan.bottle.tar.gz
######################################################################## 100,0%
==> Pouring openal-soft-1.17.2.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides OpenAL.framework.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openal-soft/lib
    CPPFLAGS: -I/usr/local/opt/openal-soft/include

==> Summary
🍺  /usr/local/Cellar/openal-soft/1.17.2: 21 files, 764.3K
```

**Comment by npomf** [comment]
OS X is a bit finicky about how it handles dynlibs, but you should be able to append the path to your `DYLD_LIBRARY_PATH` environment variable.

Executing this in your console should update it, I think:

```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/opt/openal-soft/lib
```

**Comment by arnlen** [comment]
Great, it works, thx a lot!
I'll update your README with MacOS X installation instructions. :)

**Comment by npomf** [comment]
Glad to hear it, and thank you!
